name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-parselmouth-whl:
    name: Build Parselmouth Pyodide wheel
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup Pyodide
        run: |
          pip install pyodide-build
          pyodide xbuildenv install 0.29.1

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 4.0.9
          actions-cache-folder: 'emsdk-cache'

      - name: Clone Parselmouth
        uses: actions/checkout@v6
        with:
          repository: 'YannickJadoul/Parselmouth'
          ref: 'pyodide-fixes'
          submodules: recursive

      - name: Build wheel
        run: |
          pyodide build

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: parselmouth-whl
          path: dist/praat_parselmouth-*.whl

  build-jupyterlite:
    name: Build JupyterLite
    runs-on: ubuntu-latest
    needs: build-parselmouth-whl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install the dependencies
        run: |
          pip install -r requirements.txt

      - name: Download Parselmouth wheel
        uses: actions/download-artifact@v5
        with:
          name: parselmouth-whl
          path: pypi/

      - name: Build the JupyterLite site
        run: |
          jupyter lite build --contents content --output-dir dist

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-jupyterlite
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
